using System;
using Dargon.PortableObjects;

namespace Dargon.Platform.Common {
   public class ClientDescriptor : IPortableObject {
      /// <summary>
      /// Unique Identifier generated by the client at installation.
      /// </summary>
      public Guid Id { get; set; }

      /// <summary>
      /// Name of the client, e.g. cored, dargon-manager
      /// 
      /// Null if not specified by client.
      /// </summary>
      public string Name { get; set; }

      /// <summary>
      /// Version of the client, e.g. 0.2.3-dev
      /// 
      /// Null if not specified by client.
      /// </summary>
      public string Version { get; set; }

      public void Serialize(IPofWriter writer) {
         writer.WriteGuid(0, Id);
         writer.WriteObject(1, Name);
         writer.WriteObject(2, Version);
      }

      public void Deserialize(IPofReader reader) {
         Id = reader.ReadGuid(0);
         Name = reader.ReadObject<string>(1);
         Version = reader.ReadObject<string>(2);
      }
   }
}
